---
- name: Configure the server with everything
  hosts: vms
  user: root
  roles:
    - basics
    - install_tools
    - astronvim
    - bashrc
    - role: staticdev.pyenv
      vars:
        pyenv_version: "v2.3.35"
        pyenv_virtualenv_version: "v1.2.1"
        pyenv_update_version: "172a0ed"
        pyenv_shellrc_file: "{{ ansible_env.HOME }}/.shrc"
        pyenv_path: "{{ ansible_env.HOME }}/.pyenv"
        pyenvrc_path: "{{ ansible_env.HOME }}"
        pyenv_owner: "root"
        pyenv_global:
          - 3.11.7
