---
- name: Remove local nvim
  ansible.builtin.file:
    path: "~/.config/nvim"
    state: absent

- name: Clone AstroNvim template
  ansible.builtin.git:
    repo: "https://github.com/AstroNvim/template.git"
    dest: "~/.config/nvim"
    depth: 1
    force: true

- name: Remove .git
  ansible.builtin.file:
    path: "~/.config/nvim/.git"
    state: absent

- name: Upload community.lua
  ansible.builtin.copy:
    src: ./community.lua
    dest: ~/.config/nvim/lua/

- name: Upload user.lua
  ansible.builtin.copy:
    src: ./user.lua
    dest: ~/.config/nvim/lua/plugins/

- name: Upload astroui.ua
  ansible.builtin.copy:
    src: ./astroui.lua
    dest: ~/.config/nvim/lua/plugins/

- name: Upload astrolsp.ua
  ansible.builtin.copy:
    src: ./astrolsp.lua
    dest: ~/.config/nvim/lua/plugins/

- name: Upload astrocore.ua
  ansible.builtin.copy:
    src: ./astrocore.lua
    dest: ~/.config/nvim/lua/plugins/
