---
- name: Remove local nvim
  ansible.builtin.file:
    path: "~/.config/nvim"
    state: absent

- name: Clone AstroNvim template
  ansible.builtin.git:
    repo: "https://github.com/AstroNvim/template.git"
    dest: "~/.config/nvim"
    depth: 1
    force: true

- name: Remove .git
  ansible.builtin.file:
    path: "~/.config/nvim/.git"
    state: absent
