---
dependencies:
  - role: tool
    tool_bin_name: "fzf"
    tool_version: "0.55.0"
    tool_download_url: "https://github.com/junegunn/fzf/releases/download/v{{ tool_version }}/fzf-{{ tool_version }}-linux_amd64.tar.gz"

  - role: tool
    tool_bin_name: "exa"
    tool_version: "0.10.1"
    tool_bin_path: "bin/exa"
    tool_download_url: "https://github.com/ogham/exa/releases/download/v{{ tool_version }}/exa-linux-x86_64-v{{ tool_version }}.zip"

  - role: tool
    tool_bin_name: "bat"
    tool_version: "0.24.0"
    tool_bin_path: "bat-v{{ tool_version }}-x86_64-unknown-linux-gnu/bat"
    tool_download_url: "https://github.com/sharkdp/bat/releases/download/v{{ tool_version }}/bat-v{{ tool_version }}-x86_64-unknown-linux-gnu.tar.gz"

  - role: tool
    tool_bin_name: "fd"
    tool_version: "10.2.0"
    tool_bin_path: "fd-v{{ tool_version }}-x86_64-unknown-linux-gnu/fd"
    tool_download_url: "https://github.com/sharkdp/fd/releases/download/v{{ tool_version }}/fd-v{{ tool_version }}-x86_64-unknown-linux-gnu.tar.gz"

  - role: tool
    tool_bin_name: "zoxide"
    tool_version: "0.9.6"
    tool_download_url: "https://github.com/ajeetdsouza/zoxide/releases/download/v{{ tool_version }}/zoxide-{{ tool_version }}-x86_64-unknown-linux-musl.tar.gz"

  - role: tool
    tool_bin_name: "rg"
    tool_version: "14.1.1"
    tool_bin_path: "ripgrep-{{ tool_version }}-x86_64-unknown-linux-musl/rg"
    tool_download_url: "https://github.com/BurntSushi/ripgrep/releases/download/{{ tool_version }}/ripgrep-{{ tool_version }}-x86_64-unknown-linux-musl.tar.gz"

  - role: tool
    tool_bin_name: "nvim"
    tool_version: "0.9.5"
    tool_bin_path: "nvim-linux64/bin/nvim"
    tool_custom_path: "/root"
    tool_download_url: "https://github.com/neovim/neovim/releases/download/v{{ tool_version }}/nvim-linux64.tar.gz"

  - role: tool
    tool_bin_name: "lazygit"
    tool_version: "0.44.1"
    tool_download_url: "https://github.com/jesseduffield/lazygit/releases/download/v{{ tool_version }}/lazygit_{{ tool_version }}_Linux_x86_64.tar.gz"

  - role: tool
    tool_bin_name: "navi"
    tool_version: "2.23.0"
    tool_download_url: "https://github.com/denisidoro/navi/releases/download/v{{ tool_version }}/navi-v{{ tool_version }}-x86_64-unknown-linux-musl.tar.gz"

  - role: tool
    tool_bin_name: "go"
    tool_bin_name_: "go/bin/go"
    tool_version_flag: "version"
    tool_version: "1.22.2"
    tool_download_url: "https://go.dev/dl/go{{ tool_version }}.linux-amd64.tar.gz"

  - role: tool
    tool_bin_name: direnv
    tool_version: "2.34.0"
    tool_bin_path: "direnv.linux-amd64"
    tool_download_url: "https://github.com/direnv/direnv/releases/download/v{{ tool_version }}/direnv.linux-amd64"

  - role: tool
    tool_bin_name: gdu
    tool_version: "5.29.0"
    tool_bin_path: "gdu_linux_amd64"
    tool_download_url: "https://github.com/dundee/gdu/releases/download/{{ tool_version }}/gdu_linux_amd64.tgz"
